swagger: '2.0'
info:
  description: This API will be called after the user has successfully signed up and verified the email. This API creates the user profile with all necessary details about the user such name, contact details etc.
  version: 1.0.0
  title: User Profiling
  termsOfService: Terms of service
  contact:
    name: Nirmal Kumar
    email: nirmal.kumar@socgen.com
  license:
    name: To be updated
    url: http://www.dummylicence.html
host: 'localhost:9288'
basePath: /v1
tags:
  - name: profile
    description: user's Profile
  - name: gstin
    description: user's gst number
schemes:
- http
- https
paths:
  /user/profile:
    post:
      tags:
        - profile
      summary: fetch user's details using gstin
      operationId: createProfile
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: gstin
          description: user's gst number
          required: true
          schema:
            $ref: '#/definitions/GSTIN'
        - in: header
          name: authorization
          type: string
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: string
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - profile_auth:
        - "write:profile"
      deprecated: false
securityDefinitions:
  profile_auth:
    type: "oauth2"
    authorizationUrl: "http://dummy"
    flow: "implicit"
    scopes:
      write:profile: "add new users in the database"
definitions:
  GSTIN:
    type: object
    properties:
      gstnumber:
        type: string
    title: GSTIN